# Generated by Django 2.1.7 on 2019-03-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(max_length=200)),
                ('number', models.IntegerField()),
                ('dop', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Адрес места',
                'verbose_name_plural': 'Адреса мест',
            },
        ),
    ]
