# Generated by Django 2.1.7 on 2019-03-07 15:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Galery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='person_photo')),
            ],
            options={
                'verbose_name': 'Галерея',
                'verbose_name_plural': 'Галереи',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True, verbose_name='Название')),
                ('width', models.FloatField(default=0.0, null=True, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)], verbose_name='Вес')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, null=True, verbose_name='Имя')),
                ('second_name', models.CharField(max_length=100, null=True, verbose_name='Фамилия')),
                ('third_name', models.CharField(max_length=100, null=True, verbose_name='Отчество')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('sms_mes', models.CharField(blank=True, max_length=100, null=True, verbose_name='Сообщение')),
                ('wallet', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Кошелёк')),
                ('reputation', models.FloatField(default=3.5, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(2)])),
            ],
            options={
                'verbose_name': 'Человек',
                'verbose_name_plural': 'Люди',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='TAG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=100, null=True)),
                ('width', models.FloatField(default=0.0, null=True, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)], verbose_name='Вес')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='person.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Дата/время')),
                ('summ', models.DecimalField(decimal_places=2, max_digits=30, verbose_name='Сумма')),
                ('hash_amount', models.BinaryField(max_length=200, null=True, verbose_name='Хэш сумма')),
                ('from_whom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='От_кого', to='person.Person')),
                ('price_w', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.Price')),
                ('to_whom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Кому', to='person.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True, verbose_name='Название')),
                ('unit', models.CharField(max_length=100, null=True, verbose_name='Единица измерения')),
            ],
        ),
        migrations.AddField(
            model_name='price',
            name='unit_of_measurement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='person.Units'),
        ),
        migrations.AddField(
            model_name='person',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='person.TAG'),
        ),
        migrations.AddField(
            model_name='person',
            name='users',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personshop', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='galery',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='galery', to='person.Person'),
        ),
    ]
