# Generated by Django 2.1.2 on 2018-11-03 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placeaddress',
            options={'verbose_name': 'Адрес места', 'verbose_name_plural': 'Адреса мест'},
        ),
    ]
